### ISSUE TITLE
Omit PHP release number from ".travis.yml" (7.0.33 -> 7.0)

### ISSUE THREAD

**Issue by KEINOS** [KEINOS/TPL-PHP-HelloWorld#19]
Currently, we define the exact latest version such as `7.0.33` in `.travis.yml`. Including the release number.

- https://github.com/KEINOS/TPL-PHP-HelloWorld/blob/be0497a9a7dc08920749290092211f562af43fde/.travis.yml

But omitting the release number like `7.0`, Travis will use the latest PHP of that minor version.

So the below YAML might reduce some laborious effort updating version every time PHP gets updated.

```yml
language: php

env:
  global:
  - PHAN_DISABLE_XDEBUG_WARN=1

install: /bin/bash ./.init/setup-composer.sh --dev

matrix:
  include:
    - php: 7.0
      dist: xenial
    - php: 7.1
      dist: bionic
    # Default PHP version in macOS HighSierra(10.13.6) and Mojave(10.14.4)
    - php: 7.1.23
      dist: xenial
    - php: 7.2
      dist: bionic
    - php: 7.3
      dist: bionic
    - php: 7.4
      dist: bionic
    - php: nightly
      dist: bionic
  allow_failures:
    - php: nightly

script: /bin/bash ./tests/run-tests.sh local all 
```
